spring:
  application:
    name: product
 sdasdasdasdasdasdasdasdadaasddas
    show-sql: true
eureka:
  client:sdadaasdasdadasd
    service-url:
      defaultZone: http://localhost:8761/eureka/

adasawdqdqdq
