spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springcloud?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:sdadaasdasdadasd
    service-url:
      defaultZone: http://localhost:8761/eureka/

adasawdqdqdq
